// Run: npm run db:types to generate full types from Supabase
// This is a minimal skeleton for development

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string;
          email: string;
          avatar_url: string | null;
          bio: string;
          theme: string;
          online_status: boolean;
          last_seen: string;
          privacy_message: string;
          privacy_add: string;
          privacy_profile: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name: string;
          email: string;
          avatar_url?: string | null;
          bio?: string;
          theme?: string;
          online_status?: boolean;
          last_seen?: string;
          privacy_message?: string;
          privacy_add?: string;
          privacy_profile?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      // ... other tables (generated by CLI)
    };
  };
}